from __future__ import annotations

import argparse
import difflib
import re
from pathlib import Path
from typing import NamedTuple

import yaml


GENERATED_HEADER = (
    "<!-- This file is generated by the `docs-harness` skill. "
    "Do not edit manually. -->"
)

TEXT_FILE_SUFFIXES = {
    ".md",
    ".py",
    ".sh",
    ".json",
    ".toml",
    ".yaml",
    ".yml",
    ".ts",
    ".js",
    ".go",
    ".rs",
}

# We intentionally keep env scanning narrower than generic text file traversal:
# it should focus on runtime/config sources and avoid kit-managed fixtures/templates
# that live inside the repository.
ENV_SCAN_SUFFIXES = {".py", ".js", ".ts", ".go", ".rs", ".yaml", ".yml", ".sh"}
ENV_SCAN_EXCLUDE_PREFIXES = (
    ".github/",
    "docs/",
    "specs/",
    "harness/",
    "scripts/harness/",
    "tests/harness/",
)

IGNORE_DIR_NAMES = {
    ".git",
    ".venv",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    "node_modules",
    "dist",
    "build",
}


class GenerationError(RuntimeError):
    pass


class GeneratedDocument(NamedTuple):
    rel_path: str
    content: str


BACKTICK_REF_PATTERN = re.compile(r"`((?:docs|specs)/[^`]+?)`")
MD_LINK_REF_PATTERN = re.compile(r"\[[^\]]+\]\(((?:docs|specs)/[^)\s]+)\)")
ANGLE_LINK_REF_PATTERN = re.compile(r"<((?:docs|specs)/[^>\s]+)>")


def parse_generator_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", default=".")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if generated files differ from committed versions.",
    )
    return parser.parse_args()


def parse_verify_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", default=".")
    return parser.parse_args()


def render_markdown_table(headers: list[str], rows: list[list[str]]) -> str:
    def _escape(cell: str) -> str:
        return cell.replace("|", "\\|").replace("\n", "<br>")

    header_line = "| " + " | ".join(headers) + " |"
    separator = "| " + " | ".join(["---"] * len(headers)) + " |"
    body = ["| " + " | ".join(_escape(cell) for cell in row) + " |" for row in rows]
    return "\n".join([header_line, separator, *body])


def format_file_refs(paths: list[str], *, limit: int = 4) -> str:
    if not paths:
        return "—"
    trimmed = paths[:limit]
    rendered = ", ".join(f"`{path}`" for path in trimmed)
    remaining = len(paths) - len(trimmed)
    if remaining > 0:
        rendered += f", +{remaining} more"
    return rendered


def load_yaml(repo_root: Path, rel_path: str) -> object:
    path = repo_root / rel_path
    try:
        payload = yaml.safe_load(path.read_text(encoding="utf-8"))
    except FileNotFoundError as e:
        raise GenerationError(f"missing required file: {rel_path}") from e
    return payload


def repo_relative(repo_root: Path, path: Path) -> str:
    return path.relative_to(repo_root).as_posix()


def iter_repo_text_files(repo_root: Path) -> list[Path]:
    paths: list[Path] = []
    for path in repo_root.rglob("*"):
        if not path.is_file():
            continue
        rel_path = repo_relative(repo_root, path)
        rel_parts = Path(rel_path).parts
        if any(part in IGNORE_DIR_NAMES for part in rel_parts):
            continue
        if rel_path.startswith("docs/generated/"):
            continue
        if path.suffix not in TEXT_FILE_SUFFIXES and path.name != "Dockerfile":
            continue
        paths.append(path)
    return paths


def _include_env_scan_path(*, repo_root: Path, path: Path) -> bool:
    if not path.is_file():
        return False
    rel_path = repo_relative(repo_root, path)
    rel_parts = Path(rel_path).parts
    if any(part in IGNORE_DIR_NAMES for part in rel_parts):
        return False
    if any(rel_path.startswith(prefix) for prefix in ENV_SCAN_EXCLUDE_PREFIXES):
        return False
    if path.suffix not in ENV_SCAN_SUFFIXES:
        return False
    return True


def iter_repo_env_scan_files(repo_root: Path, *, scan_roots: list[str] | None = None) -> list[Path]:
    paths: set[Path] = set()
    if scan_roots:
        for rel_root in scan_roots:
            root = (repo_root / rel_root).resolve()
            if not root.exists():
                continue
            if root.is_file():
                if _include_env_scan_path(repo_root=repo_root, path=root):
                    paths.add(root)
                continue
            for path in root.rglob("*"):
                if _include_env_scan_path(repo_root=repo_root, path=path):
                    paths.add(path)
        for path in repo_root.iterdir():
            if _include_env_scan_path(repo_root=repo_root, path=path):
                paths.add(path)
        return sorted(paths)

    for path in repo_root.rglob("*"):
        if _include_env_scan_path(repo_root=repo_root, path=path):
            paths.add(path)
    return sorted(paths)


def write_or_check(*, repo_root: Path, document: GeneratedDocument, check: bool) -> str | None:
    target = repo_root / document.rel_path
    current = target.read_text(encoding="utf-8") if target.exists() else None

    if check:
        if current != document.content:
            diff = difflib.unified_diff(
                current.splitlines() if current is not None else [],
                document.content.splitlines(),
                fromfile=f"{document.rel_path} (current)",
                tofile=f"{document.rel_path} (expected)",
                lineterm="",
            )
            diff_text = "\n".join(diff)
            return (
                f"{document.rel_path} is out of date; run the `docs-harness` generator "
                "against this repository and commit the regenerated file.\n"
                f"{diff_text}"
            )
        return None

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(document.content, encoding="utf-8")
    return None


def run_generation(
    *,
    repo_root: Path,
    documents: list[GeneratedDocument],
    check: bool,
) -> list[str]:
    errors: list[str] = []
    for document in documents:
        error = write_or_check(repo_root=repo_root, document=document, check=check)
        if error:
            errors.append(error)
    return errors


# Basic env var scanners for Python/JS/Go/Rust + `${VAR}` templates.
ENV_ASSIGNMENT_RE = re.compile("^\\s*([A-Z][A-Z0-9_]+)=(.*)$")
COMMENTED_ENV_ASSIGNMENT_RE = re.compile("^\\s*#\\s*([A-Z][A-Z0-9_]+)=(.*)$")

PYTHON_ENV_PATTERNS = [
    re.compile("os\\.getenv\\(\\s*['\\\"]([A-Z][A-Z0-9_]+)['\\\"]", re.MULTILINE),
    re.compile("os\\.environ\\.get\\(\\s*['\\\"]([A-Z][A-Z0-9_]+)['\\\"]", re.MULTILINE),
    re.compile("os\\.environ\\[\\s*['\\\"]([A-Z][A-Z0-9_]+)['\\\"]\\s*\\]", re.MULTILINE),
]

JS_ENV_PATTERNS = [
    re.compile("process\\.env\\.([A-Z][A-Z0-9_]+)\\b", re.MULTILINE),
    re.compile("process\\.env\\[\\s*['\\\"]([A-Z][A-Z0-9_]+)['\\\"]\\s*\\]", re.MULTILINE),
]

GO_ENV_PATTERNS = [
    re.compile("os\\.Getenv\\(\\s*['\\\"]([A-Z][A-Z0-9_]+)['\\\"]", re.MULTILINE),
]

RUST_ENV_PATTERNS = [
    re.compile("std::env::var\\(\\s*['\\\"]([A-Z][A-Z0-9_]+)['\\\"]", re.MULTILINE),
]

TEMPLATE_ENV_PATTERN = re.compile("\\$\\{([A-Z][A-Z0-9_]+)(?::-[^}]*)?\\}")
SHELL_ENV_PATTERN = re.compile(
    "\\$\\{([A-Z][A-Z0-9_]+)(?:(?::?[-?=+])[^}]*)\\}"
)


def normalize_repo_ref(ref: str) -> str:
    # Strip anchors and query params: `docs/x.md#y` -> `docs/x.md`.
    cleaned = ref.split("#", 1)[0].split("?", 1)[0].strip()
    return cleaned


def extract_repo_doc_refs(markdown: str) -> set[str]:
    refs: set[str] = set()
    for pattern in (BACKTICK_REF_PATTERN, MD_LINK_REF_PATTERN, ANGLE_LINK_REF_PATTERN):
        for raw in pattern.findall(markdown):
            ref = normalize_repo_ref(str(raw))
            if not ref:
                continue
            if "<" in ref or ">" in ref or "{{" in ref or "}}" in ref:
                # Patterns or templates; not a repo path reference.
                continue
            refs.add(ref)
    return refs


def parse_env_example(repo_root: Path, rel_path: str) -> dict[str, str]:
    variables: dict[str, str] = {}
    path = repo_root / rel_path
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.rstrip()
        if not line or line.lstrip().startswith("##"):
            continue
        for pattern in (ENV_ASSIGNMENT_RE, COMMENTED_ENV_ASSIGNMENT_RE):
            match = pattern.match(line)
            if not match:
                continue
            name, value = match.groups()
            variables[name] = value.strip()
            break
    return variables


def collect_env_references(
    repo_root: Path, *, env_example: str | None, scan_roots: list[str] | None = None
) -> dict[str, set[str]]:
    references: dict[str, set[str]] = {}

    def _patterns_for_path(path: Path) -> list[re.Pattern[str]]:
        suffix = path.suffix
        if suffix == ".py":
            return PYTHON_ENV_PATTERNS
        if suffix in (".js", ".ts"):
            return JS_ENV_PATTERNS
        if suffix == ".go":
            return GO_ENV_PATTERNS
        if suffix == ".rs":
            return RUST_ENV_PATTERNS
        if suffix in (".yaml", ".yml"):
            return [TEMPLATE_ENV_PATTERN]
        if suffix == ".sh":
            return [SHELL_ENV_PATTERN]
        return []

    for path in iter_repo_env_scan_files(repo_root, scan_roots=scan_roots):
        rel_path = repo_relative(repo_root, path)
        content = path.read_text(errors="ignore")
        for pattern in _patterns_for_path(path):
            for name in pattern.findall(content):
                references.setdefault(name, set()).add(rel_path)

    if env_example and (repo_root / env_example).exists():
        for name in parse_env_example(repo_root, env_example):
            references.setdefault(name, set()).add(env_example)

    return references
