from __future__ import annotations

import argparse
import difflib
from pathlib import Path
from typing import NamedTuple

import yaml


GENERATED_HEADER = (
    "<!-- This file is generated by the `observability-harness` skill. "
    "Do not edit manually. -->"
)


class GenerationError(RuntimeError):
    pass


class GeneratedDocument(NamedTuple):
    rel_path: str
    content: str


def parse_generator_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", default=".")
    parser.add_argument("--check", action="store_true")
    return parser.parse_args()


def parse_verify_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", default=".")
    return parser.parse_args()


def load_yaml(repo_root: Path, rel_path: str) -> object:
    path = repo_root / rel_path
    try:
        payload = yaml.safe_load(path.read_text(encoding="utf-8"))
    except FileNotFoundError as e:
        raise GenerationError(f"missing required file: {rel_path}") from e
    return payload


def repo_relative(repo_root: Path, path: Path) -> str:
    return path.relative_to(repo_root).as_posix()


def render_markdown_table(headers: list[str], rows: list[list[str]]) -> str:
    def _escape(cell: str) -> str:
        return cell.replace("|", "\\|").replace("\n", "<br>")

    header_line = "| " + " | ".join(headers) + " |"
    separator = "| " + " | ".join(["---"] * len(headers)) + " |"
    body = ["| " + " | ".join(_escape(cell) for cell in row) + " |" for row in rows]
    return "\n".join([header_line, separator, *body])


def write_or_check(*, repo_root: Path, document: GeneratedDocument, check: bool) -> str | None:
    target = repo_root / document.rel_path
    current = target.read_text(encoding="utf-8") if target.exists() else None
    if check:
        if current != document.content:
            diff = difflib.unified_diff(
                current.splitlines() if current is not None else [],
                document.content.splitlines(),
                fromfile=f"{document.rel_path} (current)",
                tofile=f"{document.rel_path} (expected)",
                lineterm="",
            )
            return (
                f"{document.rel_path} is out of date; run the `observability-harness` generator "
                "against this repository and commit the regenerated file.\n"
                + "\n".join(diff)
            )
        return None

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(document.content, encoding="utf-8")
    return None


def run_generation(*, repo_root: Path, documents: list[GeneratedDocument], check: bool) -> list[str]:
    errors: list[str] = []
    for document in documents:
        error = write_or_check(repo_root=repo_root, document=document, check=check)
        if error:
            errors.append(error)
    return errors
